remote_theme: patdryburgh/hitchens
hide_search: true
hide_credits: true
show_excerpts: false

#excerpt_length: 20 
#excerpt length can also be arbitrary - see how here https://jekyllrb.com/docs/posts/#post-excerpts
